project:
  type: website

website:
  title: "Quarto Website Minimal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true

shortcodes:
  - carousel.lua


